version: "3.8"

services:
  app:
    image: coollabsio/coolify:latest
    container_name: panie18-coolify
    restart: always
    working_dir: /var/www/html
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - coolify
    depends_on:
      - postgres
      - redis
      - soketi
    ports:
      - "3000:3000"
    volumes:
      - coolify_data:/app/data
    environment:
      DATABASE_HOST: coolify-db
      DATABASE_PORT: 5432
      DATABASE_NAME: coolify
      DATABASE_USERNAME: coolify
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      REDIS_HOST: coolify-redis
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      APP_KEY: ${APP_KEY}

  postgres:
    image: postgres:15-alpine
    container_name: coolify-db
    restart: always
    networks:
      - coolify
    environment:
      POSTGRES_DB: coolify
      POSTGRES_USER: coolify
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  redis:
    image: redis:7-alpine
    container_name: coolify-redis
    restart: always
    networks:
      - coolify
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]

  soketi:
    image: quay.io/soketi/soketi:latest-16-alpine
    container_name: coolify-realtime
    restart: always
    networks:
      - coolify

volumes:
  coolify_data:

networks:
  coolify:
    driver: bridge
