services:
  app:
    image: coollabsio/coolify:latest
    container_name: panie18-coolify
    restart: always
    networks:
      - coolify
    depends_on:
      - postgres
      - redis
      - soketi
    environment:
      REDIS_HOST: coolify-redis
      POSTGRES_HOST: coolify-db
    ports:
      - "3000:3000"
    volumes:
      - coolify_data:/app/data

  postgres:
    image: postgres:15-alpine
    container_name: coolify-db
    restart: always
    networks:
      - coolify
    environment:
      POSTGRES_PASSWORD: "changeme"
      POSTGRES_DB: "coolify"

  redis:
    image: redis:7-alpine
    container_name: coolify-redis
    restart: always
    networks:
      - coolify

  soketi:
    image: quay.io/soketi/soketi:latest-16-alpine
    container_name: coolify-realtime
    restart: always
    networks:
      - coolify

networks:
  coolify:
    driver: bridge

volumes:
  coolify_data:
