version: "3.8"

services:
  app:
    image: coollabsio/coolify:latest
    container_name: coolify
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - coolify_data:/app/data
      - ./data:/data
    environment:
      - NODE_ENV=production

volumes:
  coolify_data:
