```yaml
version: "3.9"

services:
  panie18-coolify:
    image: coollabsio/coolify:latest
    container_name: panie18-coolify
    restart: always
    ports:
      - "${APP_PORT}:3000"
    environment:
      DATABASE_URL: "pgsql://postgres:${POSTGRES_PASSWORD}@panie18-coolify-db:5432/coolify"
      REDIS_URL: "redis://:${REDIS_PASSWORD}@panie18-coolify-redis:6379"
      APP_KEY: "${APP_KEY}"
    depends_on:
      - panie18-coolify-db
      - panie18-coolify-redis
    networks:
      - panie18-coolify-net
    volumes:
      - coolify_data:/app/data

  panie18-coolify-db:
    image: postgres:15-alpine
    container_name: panie18-coolify-db
    restart: always
    environment:
      POSTGRES_DB: coolify
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - coolify_db:/var/lib/postgresql/data
    networks:
      - panie18-coolify-net

  panie18-coolify-redis:
    image: redis:7-alpine
    container_name: panie18-coolify-redis
    restart: always
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    volumes:
      - coolify_redis:/data
    networks:
      - panie18-coolify-net

networks:
  panie18-coolify-net:
    driver: bridge

volumes:
  coolify_data:
  coolify_db:
  coolify_redis:
