manifestVersion: 1
id: panie18-vert
name: vert
version: "1.0.0"
tagline: VERT — modern link / content hub
icon: "https://raw.githubusercontent.com/VERT-sh/VERT/main/assets/icon.png"
category: utilities
port: 3000
description: >
  VERT is a modern content hub. This Umbrel package provides an easy way to run VERT via Docker.
developer: VERT
website: https://github.com/VERT-sh/VERT
submitter: panie18
repo: https://github.com/VERT-sh/VERT
support: https://github.com/VERT-sh/VERT/issues
defaultUsername: ""
defaultPassword: ""
dependencies: []
releaseNotes: >
  Install options:
  - Use the prebuilt image (recommended for simple installs): ghcr.io/vert-sh/vert:latest
  - Or build from source if you need to change build-time PUB_* args.

  If installation fails, check container logs: docker compose -f docker-compose.yml logs -f
path: "/"
gallery: []
