version: "3.7"

services:
  glance:
    image: ghcr.io/glanceapp/glance@sha256:6df86a7e8868d1eda21f35205134b1962c422957e42a0c44d4717c8e8f741b1a
    ports:
      - 3001:3000
    volumes:
      - ./config/glance.yml:/app/config/glance.yml:ro
      - glance-data:/data
    restart: unless-stopped

volumes:
  glance-data:
