version: "3.7"
services:
  audiobookshelf:
    image: advplyr/audiobookshelf:latest
    container_name: audiobookshelf
    restart: unless-stopped
    ports:
      - "13378:80"
    volumes:
      - ${APP_DATA_DIR}/audiobookshelf:/app/audiobooks