version: "3.9"

services:
  app_proxy:
    environment:
      APP_HOST: chibisafe_server
      APP_PORT: 8001
      PROXY_AUTH_ADD: "false"
    ports:
      - "3000:3000"

  chibisafe_server:
    image: ghcr.io/chibisafe/chibisafe:latest@sha256:836467a50792b08c29d90e32447a1480208723751e8a0f7ecd7ede17fe393ea3
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
      - NODE_ENV=production
      - DATABASE_URL=postgresql://chibisafe:chibisafe@chibisafe_db:5432/chibisafe
    volumes:
      - ${APP_DATA_DIR}/uploads:/uploads
      - ${APP_DATA_DIR}/config:/config
    depends_on:
      - chibisafe_db

  chibisafe_db:
    image: postgres:16
    restart: unless-stopped
    environment:
      - POSTGRES_USER=chibisafe
      - POSTGRES_PASSWORD=chibisafe
      - POSTGRES_DB=chibisafe
    volumes:
      - ${APP_DATA_DIR}/db:/var/lib/postgresql/data
