version: "3.9"

services:
  app_proxy:
    environment:
      APP_HOST: chibisafe_server
      APP_PORT: 3000
      PROXY_AUTH_ADD: "false"

  chibisafe_server:
    image: ghcr.io/chibisafe/chibisafe:v3.6.1
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
      - NODE_ENV=production
      - CHIBISAFE_PORT=3000
    volumes:
      - ${APP_DATA_DIR}/uploads:/uploads
      - ${APP_DATA_DIR}/config:/config
