version: "3.9"

services:
  app_proxy:
    environment:
      APP_HOST: chibisafe_server
      APP_PORT: 8001
      PROXY_AUTH_ADD: "false"

  chibisafe_server:
    image: ghcr.io/chibisafe/chibisafe:latest@sha256:836467a50792b08c29d90e32447a1480208723751e8a0f7ecd7ede17fe393ea3
    restart: on-failure
    environment:
      - PUID=1000
      - PGID=1000
      - NODE_ENV=production
    volumes:
      - ${APP_DATA_DIR}/uploads:/uploads
      - ${APP_DATA_DIR}/config:/config
