version: "3.9"

services:
  app_proxy:
    environment:
      APP_HOST: chibisafe
      APP_PORT: 8001
      PROXY_AUTH_ADD: "false"
    ports:
      - "3000:3000"

  chibisafe:
    image: chibisafe/chibisafe:latest@sha256:836467a50792b08c29d90e32447a1480208723751e8a0f7ecd7ede17fe393ea3
    environment:
      - BASE_API_URL=http://chibisafe_server:8000
    expose:
      - 8001
    restart: unless-stopped

  chibisafe_server:
    image: chibisafe/chibisafe-server:latest@sha256:3da4fcbc1a183e6108cd3c02295fda5dc85acea4d6b830a0cfd7720c5d5d3c67
    environment:
      - ADMIN_PASSWORD=admin
    volumes:
      - ${APP_DATA_DIR}/database:/app/database:rw
      - ${APP_DATA_DIR}/uploads:/app/uploads:rw
      - ${APP_DATA_DIR}/logs:/app/logs:rw
    expose:
      - 8000
    restart: unless-stopped
