version: "3.7"
services:
  anonaddy:
    image: anonaddy/anonaddy:latest
    container_name: anonaddy
    restart: unless-stopped
    ports:
      - "8082:80"
    environment:
      - APP_KEY=changeme
    volumes:
      - ${APP_DATA_DIR}/anonaddy:/data