version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: mcsmanager_web
      APP_PORT: 23333
      PROXY_AUTH_ADD: "false"

  mcsmanager_web:
    image: githubyumao/mcsmanager-web:latest
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/web/data:/opt/mcsmanager/web/data
      - ${APP_DATA_DIR}/web/logs:/opt/mcsmanager/web/logs
    depends_on:
      - mcsmanager_daemon

  mcsmanager_daemon:
    image: githubyumao/mcsmanager-daemon:latest
    restart: unless-stopped
    ports:
      - "24444:24444"
    environment:
      - MCSM_DOCKER_WORKSPACE_PATH=${APP_DATA_DIR}/daemon/data/InstanceData
    volumes:
      - ${APP_DATA_DIR}/daemon/data:/opt/mcsmanager/daemon/data
      - ${APP_DATA_DIR}/daemon/logs:/opt/mcsmanager/daemon/logs
      - /var/run/docker.sock:/var/run/docker.sock
